### ISSUE TITLE
Serve sampled signals using InteractNext and Mux

### ISSUE THREAD

**Issue by rob-luke** [JuliaAudio/SampledSignals.jl#40]
This might be way outside the scope of SampledSignals.jl, but I thought I would ask...

I would like to serve a web page that can play audio stored in a `SampleBuf`, similar to how you can press pause/play/stop etc in jupyter. Ideally the user could modify some parameters using interact.

Below is a minimum (not) working example. It runs and the generated web page has the interact buttons, but it shows an error saying `SampleBuf display requires javascript`. Do you know of a way to serve generated audio to a web page?

```julia
using InteractNext, WebIO, SampledSignals

Fs = 16000

ui = @manipulate for time_seconds = [1, 2, 3]
    x = randn(Fs * time_seconds, 2);  
    a = SampleBuf(x, Fs)
end

using Mux
responder(req) = ui
webio_serve(page("/", responder))
```

**Comment by ssfrr** [comment]
In order for the javascript display stuff  to work there's some initialization code that needs to be part of the DOM. In a jupyter notebook that happens when you run `using SampledSignals` (it dumps the proper js initialization code into the output of that cell). If you look at the code for [`embed_javascript()`](https://github.com/JuliaAudio/SampledSignals.jl/blob/54d136cfe06b1c9bfdab4eb45733638e8a15ff44/src/WAVDisplay.jl#L6-L19) you can see how it works.

If you can get that output dumped to the DOM inside of the `Mux` page than the audio display should work as it does in the notebook.

Doing streaming audio to the browser is definitely more complicated, as you'd need to open up a websocket or something to continuously pass the generated audio through. One of the things I've done in the past is use `PortAudio.jl` to output the sound directly from Julia (not going through the browser), but still control the process with `Interact` sliders. Of course this only works if you're working locally, and the computer you're running Julia on is the same as the one you're sitting at.

**Comment by rob-luke** [comment]
Thanks for the information @ssfrr. I will take a look at `embed_javascript()`.  

I have been using `PortAudio.jl` with `Interact` locally and it works perfectly, thanks for the great packages.
