### ISSUE TITLE
VST plugin in Julia

### ISSUE THREAD

**Issue by aminya** [JuliaAudio/SampledSignals.jl#54]
Is there a way to create a VST plugin using Julia?

MATLAB allows this through converting to C/C++ code. 
https://www.mathworks.com/help/audio/audio-plugin-creation-and-hosting.html

There is also FAUST
http://faust.grame.fr/

**Comment by ssfrr** [comment]
There isn't currently any infrastructure for generating VSTs. It might be possible to use [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) to compile your audio processing code into a shared library that could be loaded as a VST though. You'd want to be careful in your code to make sure you don't allocate any memory in the audio processing function, but it seems like it should likely work.

I'm going to close the issue, not because it's not a good idea but because it's not something I have plans to implement any time soon. I'd definitely like to see a demo of it working!
