### ISSUE TITLE
Outdated compatibility constraints with, e.g., FixedPointNumbers

### ISSUE THREAD

**Issue by vvbond** [JuliaAudio/SampledSignals.jl#64]
The package can't be installed with the recent version of FixedPointNumbers.jl v0.8.4 due to compatibility constraints.

**Comment by PallHaraldsson** [comment]
FYI: fixed by my (see there how you can without waiting for tag): https://github.com/JuliaAudio/SampledSignals.jl/pull/65

```
(@v1.6) pkg> add FixedPointNumbers@v0.8.4
```

[installs 44 (plus 9 artifacts), e.g.] 
Installed NicePipes ──────────────────── v0.1.3
[..]
Installed Genie ──────────────────────── v1.12.0

downgraded one for me:
  [c8ffd9c3] ↓ MbedTLS_jll v2.25.0+0 ⇒ v2.24.0+1

**Comment by ma-laforge** [comment]
Agreed. The `[compat]` section of Project.toml requires `FixedPointNumbers` to be between `v0.6.1 - v0.6.*`.

It should probably be changed to something like:
```
[compat]
FixedPointNumbers = "0.6.1, 0.7, 0.8"
```

(Assuming the new versions of `FixedPointNumbers` do not break `SampledSignals.jl`).

**Comment by rob-luke** [comment]
I am in the process of updating the CIs and then will manually update these compats. Moving forward, we have installed CompatHelper to ensure we are using recent versions of dependencies.

I will ping back this issue when I think its addressed. Probably take me a week or two.

**Comment by rob-luke** [comment]
I have updated the compats. Could you please see if the latest release solves your issues? Thanks

**Comment by rob-luke** [comment]
Closing. Please reopen if your issue persists
